---
galaxy_info:
  author: David Ribeiro
  description: Student
  company: 42Mulhouse.fr
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags:
    - security
    - vault
    - secrets
    - persistence
    - atomic-operations

dependencies: []
